SITE_IDS = {
    'test1.bizwiggle.com': 1,
    'test2.bizwiggle.com': 2,
    'zachowellpainting.com':3,
    'painting.bizwiggle.com':4,
    'painting1.bizwiggle.com':5,
    'painting2.bizwiggle.com':6,
    'painting3.bizwiggle.com':7,
    'painting4.bizwiggle.com':8,
    'painting5.bizwiggle.com':9,
    'painting6.bizwiggle.com':10,
    'painting7.bizwiggle.com':11,
    'painting8.bizwiggle.com':12,
    'painting9.bizwiggle.com':13,
    'painting10.bizwiggle.com':14,
    'painting11.bizwiggle.com':15,
    'painting12.bizwiggle.com':16,
    'painting13.bizwiggle.com':17,
    'painting14.bizwiggle.com':18,
    'painting15.bizwiggle.com':19,
    'colorcoat1.com':20,
}

BIZWIGGLE_INFO = {
    'phone':'(512)843-2631',
    'email':'admin@bizwiggle.com',
}

BANNER_LINE_LENGTH = 40

DAYS_BETWEEN_BILLING_CHECK = 14

STATES = (
    ('  ', 'Select Your State'), 
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Deleware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming')
)
